[project]
name = "ticman"
version = "0.1.0"
authors = [
    { name = "Oscar Adrián Castán López" },
    { name = "Martín Zamorano Acuña" },
]
requires-python = ">=3.8"
license = "MIT"

[project.scripts]
ticman = "ticman.main:main"
